"""Curated caption presets tailored for vertical 9:16 Shorts, TikTok, and Reels."""
from typing import Any

CAPTION_PRESETS: dict[str, dict[str, Any]] = {
    "crime_red": {
        "name": "Crime Red Alert",
        "font": "Anton",
        "font_face": "Regular",
        "size": 64,
        "uppercase": True,
        "color": "#FFFFFF",
        "outline": "#000000",
        "outline_width": 6,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_blur": 4.0,
        "shadow_opacity": 85.0,
        "glow_enabled": True,
        "glow_follow_color": False,
        "glow_color": "#FF2233",
        "glow_radius": 14.0,
        "glow_opacity": 70.0,
        "highlight": "#FF2233",
        "animation": "punch",
        "position_x": 0.5,
        "position_y": 0.72,
    },
    "viral_yellow": {
        "name": "Viral TikTok Yellow",
        "font": "Anton",
        "font_face": "Regular",
        "size": 64,
        "uppercase": True,
        "color": "#FFFFFF",
        "outline": "#000000",
        "outline_width": 7,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_blur": 3.0,
        "shadow_opacity": 80.0,
        "glow_enabled": True,
        "glow_follow_color": False,
        "glow_color": "#FFE600",
        "glow_radius": 12.0,
        "glow_opacity": 65.0,
        "highlight": "#FFE600",
        "animation": "pop",
        "position_x": 0.5,
        "position_y": 0.72,
    },
    "cyber_cyan": {
        "name": "Cyber Neon Cyan",
        "font": "Montserrat",
        "font_face": "Bold",
        "size": 62,
        "uppercase": True,
        "color": "#00F0FF",
        "outline": "#050B14",
        "outline_width": 6,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_blur": 4.0,
        "shadow_opacity": 80.0,
        "glow_enabled": True,
        "glow_follow_color": True,
        "glow_color": "#00F0FF",
        "glow_radius": 15.0,
        "glow_opacity": 75.0,
        "highlight": "#00F0FF",
        "animation": "punch",
        "position_x": 0.5,
        "position_y": 0.72,
    },
    "mrbeast_gold": {
        "name": "MrBeast Gold",
        "font": "Anton",
        "font_face": "Regular",
        "size": 68,
        "uppercase": True,
        "color": "#FFD700",
        "outline": "#000000",
        "outline_width": 8,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_blur": 5.0,
        "shadow_opacity": 90.0,
        "glow_enabled": False,
        "highlight": "#FFFFFF",
        "animation": "pop",
        "position_x": 0.5,
        "position_y": 0.72,
    },
    "clean_card": {
        "name": "Clean Minimal Card",
        "font": "Poppins",
        "font_face": "Bold",
        "size": 46,
        "uppercase": False,
        "color": "#FFFFFF",
        "outline": "#000000",
        "outline_width": 0,
        "shadow_enabled": False,
        "background_enabled": True,
        "background_color": "#000000",
        "background_opacity": 80.0,
        "background_radius": 0.015,
        "background_override": False,
        "highlight": "#FFE600",
        "animation": "fade",
        "position_x": 0.5,
        "position_y": 0.75,
    },
}
