"""Curated CapCut-style caption templates with unique typography, animations, glows, boxes, and emojis."""
from typing import Any

CAPTION_TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "none",
        "name": "No Template",
        "badge": "",
        "preview_text": "",
        "is_none": True,
    },
    {
        "id": "capcut_emoji_pop",
        "name": "CapCut Emoji",
        "badge": "Emoji",
        "preview_text": "CURIOUS ABOUT",
        "font": "Komika Axis",
        "font_face": "Bold",
        "size": 68,
        "uppercase": True,
        "color": "#FFFFFF",
        "highlight": "#FFE600",
        "outline": "#000000",
        "outline_width": 7,
        "animation": "emoji pop",
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_x": 3.0,
        "shadow_y": 3.0,
        "shadow_blur": 5.0,
        "shadow_opacity": 90.0,
        "glow_enabled": False,
        "background_enabled": False,
        "emojis": ["🙈", "💡", "🔥"],
    },
    {
        "id": "neon_glow",
        "name": "Neon Glow",
        "badge": "Neon Glow",
        "preview_text": "BROWN FOX",
        "font": "Montserrat",
        "font_face": "Bold",
        "size": 64,
        "uppercase": True,
        "color": "#FFFFFF",
        "highlight": "#FF2A85",
        "outline": "#000000",
        "outline_width": 5,
        "animation": "pop",
        "glow_enabled": True,
        "glow_follow_color": False,
        "glow_color": "#FF2A85",
        "glow_radius": 16.0,
        "glow_opacity": 80.0,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_x": 3.0,
        "shadow_y": 3.0,
        "shadow_blur": 4.0,
        "shadow_opacity": 80.0,
        "background_enabled": False,
    },
    {
        "id": "hormozi_yellow",
        "name": "Hormozi Karaoke",
        "badge": "Karaoke",
        "preview_text": "THE QUICK",
        "font": "Komika Axis",
        "font_face": "Bold",
        "size": 68,
        "uppercase": True,
        "color": "#FFFFFF",
        "highlight": "#FFE600",
        "outline": "#000000",
        "outline_width": 8,
        "animation": "karaoke",
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_x": 4.0,
        "shadow_y": 4.0,
        "shadow_blur": 5.0,
        "shadow_opacity": 90.0,
        "glow_enabled": False,
        "background_enabled": False,
    },
    {
        "id": "active_box_purple",
        "name": "Box Tag Focus",
        "badge": "Box Tag",
        "preview_text": "THE QUICK",
        "font": "Montserrat",
        "font_face": "Bold",
        "size": 60,
        "uppercase": True,
        "color": "#FFFFFF",
        "highlight": "#8B5CF6",
        "outline": "#000000",
        "outline_width": 4,
        "animation": "word highlight",
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_x": 2.0,
        "shadow_y": 2.0,
        "shadow_blur": 4.0,
        "shadow_opacity": 80.0,
        "background_enabled": False,
    },
    {
        "id": "mrbeast_gold",
        "name": "MrBeast Punch",
        "badge": "Punch",
        "preview_text": "GOLD",
        "font": "Komika Axis",
        "font_face": "Bold",
        "size": 70,
        "uppercase": True,
        "color": "#FFD700",
        "highlight": "#FFFFFF",
        "outline": "#000000",
        "outline_width": 8,
        "animation": "punch",
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_x": 4.0,
        "shadow_y": 4.0,
        "shadow_blur": 5.0,
        "shadow_opacity": 90.0,
        "glow_enabled": False,
        "background_enabled": False,
    },
    {
        "id": "comic_bounce",
        "name": "Comic Bounce",
        "badge": "Bounce",
        "preview_text": "BOUNCE",
        "font": "Komika Axis",
        "font_face": "Bold",
        "size": 66,
        "uppercase": True,
        "color": "#FFDD00",
        "highlight": "#FF2A85",
        "outline": "#1A102F",
        "outline_width": 7,
        "animation": "bounce",
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_x": 4.0,
        "shadow_y": 4.0,
        "shadow_blur": 4.0,
        "shadow_opacity": 90.0,
        "glow_enabled": False,
        "background_enabled": False,
    },
    {
        "id": "fire_gradient",
        "name": "Fiery Flame",
        "badge": "Flame",
        "preview_text": "FIRE",
        "font": "Impact",
        "font_face": "Regular",
        "size": 70,
        "uppercase": True,
        "color": "#FF4500",
        "highlight": "#FFE600",
        "outline": "#1A0500",
        "outline_width": 7,
        "animation": "punch",
        "glow_enabled": True,
        "glow_follow_color": False,
        "glow_color": "#FF6B00",
        "glow_radius": 16.0,
        "glow_opacity": 75.0,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_x": 3.0,
        "shadow_y": 3.0,
        "shadow_blur": 5.0,
        "shadow_opacity": 85.0,
        "background_enabled": False,
    },
    {
        "id": "cinematic_serif",
        "name": "Cinematic Serif",
        "badge": "Serif",
        "preview_text": "Cinematic",
        "font": "Baskerville Old Face",
        "font_face": "Italic",
        "size": 54,
        "uppercase": False,
        "color": "#F8FAFC",
        "highlight": "#FDE047",
        "outline": "#000000",
        "outline_width": 3,
        "animation": "fade",
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_x": 2.0,
        "shadow_y": 2.0,
        "shadow_blur": 4.0,
        "shadow_opacity": 80.0,
        "background_enabled": False,
    },
    {
        "id": "clean_minimal_card",
        "name": "Clean Minimal Pill",
        "badge": "Pill",
        "preview_text": "Minimal",
        "font": "Poppins",
        "font_face": "Bold",
        "size": 46,
        "uppercase": False,
        "color": "#FFFFFF",
        "highlight": "#FFE600",
        "outline": "#000000",
        "outline_width": 0,
        "animation": "fade",
        "shadow_enabled": False,
        "background_enabled": True,
        "background_color": "#0F1117",
        "background_opacity": 80.0,
        "background_radius": 0.015,
        "background_override": False,
    },
    {
        "id": "tilted_sport",
        "name": "Tilted Energy",
        "badge": "Sport",
        "preview_text": "ENERGY",
        "font": "Montserrat",
        "font_face": "Bold Italic",
        "size": 64,
        "uppercase": True,
        "color": "#22C55E",
        "highlight": "#FFFFFF",
        "outline": "#000000",
        "outline_width": 6,
        "animation": "pop",
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_x": 3.0,
        "shadow_y": 3.0,
        "shadow_blur": 4.0,
        "shadow_opacity": 85.0,
        "background_enabled": False,
    },
    {
        "id": "solid_yellow_card",
        "name": "Cartoon Yellow Box",
        "badge": "Cartoon",
        "preview_text": "CARTOON",
        "font": "Komika Axis",
        "font_face": "Bold",
        "size": 66,
        "uppercase": True,
        "color": "#111827",
        "highlight": "#FFFFFF",
        "outline": "#111827",
        "outline_width": 0,
        "animation": "pop",
        "shadow_enabled": False,
        "background_enabled": True,
        "background_color": "#FFDE00",
        "background_outline": "#000000",
        "background_outline_width": 4.0,
        "background_radius": 0.02,
        "background_opacity": 100.0,
        "background_override": False,
    },
]

CAPTION_TEMPLATES_BY_ID: dict[str, dict[str, Any]] = {t["id"]: t for t in CAPTION_TEMPLATES}

# Backwards compatibility aliases
_ALIASES = {
    "double_emoji_pop": "capcut_emoji_pop",
    "neon_cyber_cyan": "neon_glow",
    "neon_amber_gold": "neon_glow",
    "neon_hot_pink": "neon_glow",
    "neon_lime_green": "neon_glow",
    "white_soft_halo": "neon_glow",
    "karaoke_lime": "hormozi_yellow",
    "karaoke_cyan": "hormozi_yellow",
    "active_box_red": "active_box_purple",
    "active_box_green": "active_box_purple",
}

for _alias, _target in _ALIASES.items():
    if _target in CAPTION_TEMPLATES_BY_ID:
        CAPTION_TEMPLATES_BY_ID[_alias] = CAPTION_TEMPLATES_BY_ID[_target]


def get_template(template_id: str) -> dict[str, Any] | None:
    return CAPTION_TEMPLATES_BY_ID.get(template_id)
